version: "3.8"

services:
  django:
    build:
      dockerfile: Dockerfile
      context: ./backend_controller
    volumes:
      - ./backend_controller:/api
    ports:
      - 8000:8000
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: database
    ports:
      - 5432:5432

  postgres_admin:
    image: dpage/pgadmin4:6.0
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - 5050:80
